name: Show Python Version

on:
  push:
  workflow_dispatch:

jobs:
  show-python-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show Python version
        run: python --version
